src/Entity/Comments.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommentsRepository")
 */
class Comments
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     */
    private $UserId;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Content;

    /**
     * @ORM\Column(type="time")
     */
    private $Time;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserId(): ?User
    {
        return $this->UserId;
    }

    public function setUserId(?User $UserId): self
    {
        $this->UserId = $UserId;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->Content;
    }

    public function setContent(string $Content): self
    {
        $this->Content = $Content;

        return $this;
    }

    public function getTime(): ?\DateTimeInterface
    {
        return $this->Time;
    }

    public function setTime(\DateTimeInterface $Time): self
    {
        $this->Time = $Time;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 *  @UniqueEntity(fields={"name"}, message="There is already an account with this name")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="array")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string",length=100)
     */
    private $password;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $result;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $comments;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $prediction;

    /**
     * @ORM\Column(type="string", length=190,unique=true)
     */
    private $name;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Blocked;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\FavClubs", mappedBy="userId")
     */
    private $favClubs;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\FavPlayer", mappedBy="userId")
     */
    private $favPlayers;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\FavMatches", mappedBy="userId")
     */
    private $favMatches;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Predictions", mappedBy="userId")
     */
    private $predictions;

    public function __construct()
    {
        $this->favClubs = new ArrayCollection();
        $this->favPlayers = new ArrayCollection();
        $this->favMatches = new ArrayCollection();
        $this->predictions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getResult(): ?int
    {
        return $this->result;
    }

    public function setResult(?int $result): self
    {
        $this->result = $result;

        return $this;
    }

    public function getComments(): ?string
    {
        return $this->comments;
    }

    public function setComments(?string $comments): self
    {
        $this->comments = $comments;

        return $this;
    }

    public function getPrediction(): ?string
    {
        return $this->prediction;
    }

    public function setPrediction(?string $prediction): self
    {
        $this->prediction = $prediction;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getBlocked(): ?bool
    {
        return $this->Blocked;
    }

    public function setBlocked(bool $Blocked): self
    {
        $this->Blocked = $Blocked;

        return $this;
    }

    /**
     * @return Collection|FavClubs[]
     */
    public function getFavClubs(): Collection
    {
        return $this->favClubs;
    }

    public function addFavClub(FavClubs $favClub): self
    {
        if (!$this->favClubs->contains($favClub)) {
            $this->favClubs[] = $favClub;
            $favClub->addUserId($this);
        }

        return $this;
    }

    public function removeFavClub(FavClubs $favClub): self
    {
        if ($this->favClubs->contains($favClub)) {
            $this->favClubs->removeElement($favClub);
            $favClub->removeUserId($this);
        }

        return $this;
    }

    /**
     * @return Collection|FavPlayer[]
     */
    public function getFavPlayers(): Collection
    {
        return $this->favPlayers;
    }

    public function addFavPlayer(FavPlayer $favPlayer): self
    {
        if (!$this->favPlayers->contains($favPlayer)) {
            $this->favPlayers[] = $favPlayer;
            $favPlayer->addUserId($this);
        }

        return $this;
    }

    public function removeFavPlayer(FavPlayer $favPlayer): self
    {
        if ($this->favPlayers->contains($favPlayer)) {
            $this->favPlayers->removeElement($favPlayer);
            $favPlayer->removeUserId($this);
        }

        return $this;
    }

    /**
     * @return Collection|FavMatches[]
     */
    public function getFavMatches(): Collection
    {
        return $this->favMatches;
    }

    public function addFavMatch(FavMatches $favMatch): self
    {
        if (!$this->favMatches->contains($favMatch)) {
            $this->favMatches[] = $favMatch;
            $favMatch->addUserId($this);
        }

        return $this;
    }

    public function removeFavMatch(FavMatches $favMatch): self
    {
        if ($this->favMatches->contains($favMatch)) {
            $this->favMatches->removeElement($favMatch);
            $favMatch->removeUserId($this);
        }

        return $this;
    }

    /**
     * @return Collection|Predictions[]
     */
    public function getPredictions(): Collection
    {
        return $this->predictions;
    }

    public function addPrediction(Predictions $prediction): self
    {
        if (!$this->predictions->contains($prediction)) {
            $this->predictions[] = $prediction;
            $prediction->addUserId($this);
        }

        return $this;
    }

    public function removePrediction(Predictions $prediction): self
    {
        if ($this->predictions->contains($prediction)) {
            $this->predictions->removeElement($prediction);
            $prediction->removeUserId($this);
        }

        return $this;
    }
}

templates/myProfile/admin-comments.html.twig
{% extends 'myProfile/admin.html.twig' %}

{% block title %}Football results{% endblock %}
{% block body %}
{{ parent() }}
<br>
<form method="POST">
<h4 align="center">Comments</h4><br>
<div style="width: 70%;margin:0 auto;">
    <div style="height:335px;overflow-y: auto;">
            <a href="{{ path('adminCommentsD') }}" class="btn btn-primary">Clear all</a>
<table class="table table-bordered">
    {% for comment in comments %}
    <tr>
        <th style="width: 15%">{{ comment.userId.name }}</th>
        <th>{{ comment.content }}</th>
        <th style="width: 15%">{{ comment.time|date("H:i:s") }}</th>
    </tr>
    {% endfor %}
</table>
    </div>
<div class="input-group mb-3">
        <input type="text" class="form-control" id="newComment" name="newComment" placeholder="Write a comment" aria-label="Write a comment" aria-describedby="button-addon2">
        <div class="input-group-append">
          <button class="btn btn-outline-primary" type="submit" id="button-addon2">Post</button>
        </div>
    </div>
</div>
</form>
{% endblock %}

templates/myProfile/admin-createQuiz.html.twig
{% extends 'myProfile/admin.html.twig' %}

{% block title %}Football results{% endblock %}
{% block body %}
{{ parent() }}
<br>
<div class="float-left" style="width: 50%;margin-left: 5%">
    <form method="post">
        <h4>Create new quiz</h4><br>
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text">Quiz name:</span>
            </div>
            <input type="text" class="form-control" id="name" name="name">
        </div>
            <br>
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text">Question 1 and answer:</span>
            </div>
            <input type="text"  id="quest1" name="quest1" class="form-control">
            <input type="text" id="ans1correct" name="ans1correct" class="form-control">
        </div>
        <p>3 possible answers:</p>
        <input type="text" id="ans1a" name="ans1a" class="form-control">
        <input type="text" id="ans1b" name="ans1b" class="form-control">
        <input type="text" id="ans1c" name="ans1c" class="form-control">
        <br><br>
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text">Question 2 and answer:</span>
            </div>
            <input type="text"  id="quest2" name="quest2" class="form-control">
            <input type="text" id="ans2correct" name="ans2correct" class="form-control">
            </div>
        <p>3 possible answers:</p>
        <input type="text" id="ans2a" name="ans2a" class="form-control">
        <input type="text" id="ans2b" name="ans2b" class="form-control">
        <input type="text" id="ans2c" name="ans2c" class="form-control">
        
        <br><br>
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text">Question 3 and answer:</span>
            </div>
            <input type="text"  id="quest3" name="quest3" class="form-control">
            <input type="text" id="ans3correct" name="ans3correct" class="form-control">
            </div>
        <p>3 possible answers:</p>
        <input type="text" id="ans3a" name="ans3a" class="form-control">
        <input type="text" id="ans3b" name="ans3b" class="form-control">
        <input type="text" id="ans3c" name="ans3c" class="form-control">

        <br><br>
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text">Question 4 and answer:</span>
            </div>
            <input type="text"  id="quest4" name="quest4" class="form-control">
            <input type="text" id="ans4correct" name="ans4correct" class="form-control">
            </div>
        <p>3 possible answers:</p>
        <input type="text" id="ans4a" name="ans4a" class="form-control">
        <input type="text" id="ans4b" name="ans4b" class="form-control">
        <input type="text" id="ans4c" name="ans4c" class="form-control">

        <br><br>
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text">Question 5 and answer:</span>
            </div>
            <input type="text"  id="quest5" name="quest5" class="form-control">
            <input type="text" id="ans5correct" name="ans5correct" class="form-control">
            </div>
        <p>3 possible answers:</p>
        <input type="text" id="ans5a" name="ans5a" class="form-control">
        <input type="text" id="ans5b" name="ans5b" class="form-control">
        <input type="text" id="ans5c" name="ans5c" class="form-control">
            <br>
         <button class="btn btn-outline-primary my-2 my-sm-0"  id="submit" name="submit" type="submit">Upload quiz</button>
    </form>
</div>


<div class="float-right" style="width: 35%">
        <h4 align="center">All trivia</h4><br>
        <table class="table table-striped">
            {% for quiz in quizAll %}
            <tr>
                <th><a href="{{ path('adminQuizLook',{id: quiz.id}) }}">{{ quiz.name }}</a></th>
                <th><a href="{{ path('adminQuizD',{id: quiz.id}) }}" class="btn btn-primary">Delete</a></th>
            </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

templates/myProfile/admin-editQuiz.html.twig
{% extends 'myProfile/admin.html.twig' %}

{% block title %}Football results{% endblock %}
{% block body %}
{{ parent() }}
<br>
<div style="width: 55%;margin:0 auto;">
    <form method="post">
        <h4 align="center">Edit quiz</h4><br>
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text">Quiz name:</span>
            </div>
            <input type="text" class="form-control" id="name" name="name" value="{{ quiz.name }}">
        </div>
            <br>
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text">Question 1 and answer:</span>
            </div>
            <input type="text"  id="quest1" name="quest1" class="form-control" value="{{ quiz.quest1 }}">
            <input type="text" id="ans1correct" name="ans1correct" class="form-control" value="{{ quiz.ans1correct }}">
        </div>
        <p>3 possible answers:</p>
        <input type="text" id="ans1a" name="ans1a" class="form-control" value="{{ quiz.ans1a }}">
        <input type="text" id="ans1b" name="ans1b" class="form-control" value="{{ quiz.ans1b }}">
        <input type="text" id="ans1c" name="ans1c" class="form-control" value="{{ quiz.ans1c }}">
        <br><br>
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text">Question 2 and answer:</span>
            </div>
            <input type="text"  id="quest2" name="quest2" class="form-control" value="{{ quiz.quest2 }}">
            <input type="text" id="ans2correct" name="ans2correct" class="form-control" value="{{ quiz.ans2correct }}">
            </div>
        <p>3 possible answers:</p>
        <input type="text" id="ans2a" name="ans2a" class="form-control" value="{{ quiz.ans2a }}">
        <input type="text" id="ans2b" name="ans2b" class="form-control" value="{{ quiz.ans2b }}">
        <input type="text" id="ans2c" name="ans2c" class="form-control" value="{{ quiz.ans2c }}">
        
        <br><br>
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text">Question 3 and answer:</span>
            </div>
            <input type="text"  id="quest3" name="quest3" class="form-control" value="{{ quiz.quest3 }}">
            <input type="text" id="ans3correct" name="ans3correct" class="form-control" value="{{ quiz.ans3correct }}">
            </div>
        <p>3 possible answers:</p>
        <input type="text" id="ans3a" name="ans3a" class="form-control" value="{{ quiz.ans3a }}">
        <input type="text" id="ans3b" name="ans3b" class="form-control" value="{{ quiz.ans3b }}">
        <input type="text" id="ans3c" name="ans3c" class="form-control" value="{{ quiz.ans3c }}">

        <br><br>
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text">Question 4 and answer:</span>
            </div>
            <input type="text"  id="quest4" name="quest4" class="form-control" value="{{ quiz.quest4 }}">
            <input type="text" id="ans4correct" name="ans4correct" class="form-control" value="{{ quiz.ans4correct }}">
            </div>
        <p>3 possible answers:</p>
        <input type="text" id="ans4a" name="ans4a" class="form-control" value="{{ quiz.ans4a }}">
        <input type="text" id="ans4b" name="ans4b" class="form-control" value="{{ quiz.ans4b }}">
        <input type="text" id="ans4c" name="ans4c" class="form-control" value="{{ quiz.ans4c }}">

        <br><br>
        <div class="input-group">
            <div class="input-group-prepend">
                <span class="input-group-text">Question 5 and answer:</span>
            </div>
            <input type="text"  id="quest5" name="quest5" class="form-control" value="{{ quiz.quest5 }}">
            <input type="text" id="ans5correct" name="ans5correct" class="form-control" value="{{ quiz.ans5correct }}">
            </div>
        <p>3 possible answers:</p>
        <input type="text" id="ans5a" name="ans5a" class="form-control" value="{{ quiz.ans5a }}">
        <input type="text" id="ans5b" name="ans5b" class="form-control" value="{{ quiz.ans5b }}">
        <input type="text" id="ans5c" name="ans5c" class="form-control" value="{{ quiz.ans5c }}">
            <br>
         <button class="btn btn-outline-primary my-2 my-sm-0"  id="submit" name="submit" type="submit">Update quiz</button>
    </form>
</div>

{% endblock %}

templates/myProfile/admin-searchUser.html.twig
{% extends 'myProfile/admin.html.twig' %}

{% block title %}Football results{% endblock %}
{% block body %}
{{ parent() }}
<br>

<div style="width: 50%;margin:0 auto;">
    <h4 align="center">Users</h4><br>
    <table class="table table-striped">
        <tr>
            {% if userDB != null %}
                <th>{{ userDB.name }}</th>
                {% if userDB.blocked == 0 %}
                <th><a href="{{ path('adminUsersB',{id: userDB.id}) }}" class="btn btn-primary">Block</a></th>
                {% else %}
                    <th><a href="{{ path('adminUsersU',{id: userDB.id}) }}" class="btn btn-primary">Unblock</a></th>
                {% endif %}
                <th><a href="{{ path('adminUsersD',{id: userDB.id}) }}" class="btn btn-primary">Delete</a></th>
            {% else %}
                <th rowspan="3">User cannot be found.</th>
            {% endif %}
        </tr>
    </table>
</div>
 {% endblock %}

templates/myProfile/admin-users.html.twig
{% extends 'myProfile/admin.html.twig' %}

{% block title %}Football results{% endblock %}
{% block body %}
{{ parent() }}
<br>
<form method="post">
<div class="float-left" style="width: 25%;display: flex">
        <input class="form-control mr-sm-2" style="width: 40%" type="search" id="searchUser" name="searchUser" placeholder="Search user" aria-label="Search">
        <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button></div>
</div>

<div style="width: 50%;margin:0 auto;">
    <h4 align="center">Users</h4><br>
    <table class="table table-striped">
        {% for userDB in usersDB %}
        <tr>
            <th>{{ userDB.name }}</th>
            {% if userDB.blocked == 0 %}
            <th><a href="{{ path('adminUsersB',{id: userDB.id}) }}" class="btn btn-primary">Block</a></th>
            {% else %}
                <th><a href="{{ path('adminUsersU',{id: userDB.id}) }}" class="btn btn-primary">Unblock</a></th>
            {% endif %}
            <th><a href="{{ path('adminUsersD',{id: userDB.id}) }}" class="btn btn-primary">Delete</a></th>
        </tr>
        {% endfor %}
    </table>
</div>
</form>
{% endblock %}

templates/myProfile/admin.html.twig
{% extends 'base.html.twig' %}

{% block title %}Football results{% endblock %}
{% block body %}
{{ parent() }}
<ul class="nav nav-tabs" style="background:linear-gradient(to right,#66ccff -3%, #3366cc 100%);margin-top: -0.1%">
  <li class="nav-item">
      <a class="nav-link" href="{{ path('adminUsers')}}" style="color: black">Users</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{{ path('adminComments')}}" style="color: black">Comments</a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="{{ path('adminQuiz')}}" style="color: black">Quiz</a>
    </li>
</ul>
{% endblock %}

templates/myProfile/user-comments.html.twig
{% extends 'myProfile/user.html.twig' %}

{% block title %}Football results{% endblock %}
{% block body %}
{{ parent() }}
<br>
<form method="POST">
<h4 align="center">Comments</h4><br>
<div style="width: 70%;margin:0 auto;">
    <div style="height:335px;overflow-y: auto;">
<table class="table table-bordered">
    {% for comment in comments %}
    <tr>
        <th style="width: 15%">{{ comment.userId.name }}</th>
        <th>{{ comment.content }}</th>
        <th style="width: 15%">{{ comment.time|date("H:i:s") }}</th>
    </tr>
    {% endfor %}
</table>
    </div>
<div class="input-group mb-3">
        <input type="text" class="form-control" id="newComment" name="newComment" placeholder="Write a comment" aria-label="Write a comment" aria-describedby="button-addon2">
        <div class="input-group-append">
          <button class="btn btn-outline-primary" type="submit" id="button-addon2">Post</button>
        </div>
      </div>
</div>
</form>
{% endblock %}

templates/myProfile/user-favourites.html.twig
{% extends 'myProfile/user.html.twig' %}

{% block title %}Football results{% endblock %}
{% block body %}
{{ parent() }}
<br>
<h4 align="center">Favourites</h4><br>
<div class="float-left" style="width: 24%">
<h4>Teams</h4><br>
            <table class="table table-striped">
                <tr>
                    <th>Name</th>
                    <th></th>
                </tr>
                {% for club in favClubs %}
                <tr>
                   <td><a href="{{ path('selectedTeam', {name: club.leagueName,id: club.leagueId,tid: club.clubId}) }}"> 
                        {{ club.clubName}} </a></td>
                <td>
                    <a href="{{ path('delFavClub',{cid: club.id}) }}" class="btn btn-outline-primary btn-sm">Unfollow</a>
                </td>
                </tr>
                {% endfor %}
            </table>
</div>

<div class="float-left" style="width: 24%;margin-left: 2%;margin-right: 2%">
<h4>Players</h4><br>
            <table class="table table-striped">
                <tr>
                    <th>Name</th>
                    <th></th>
                </tr>
                {% for player in favPlayers %}
                <tr>
                   <td><a href="{{ path('selectedPlayer', {name: player.leagueName,id: player.leagueId,tid: player.clubId,pid: player.playerId}) }}"> 
                        {{ player.playerName}} </a></td>
                <td>
                    <a href="{{ path('delFavPlayer',{pid: player.id}) }}" class="btn btn-outline-primary btn-sm">Unfollow</a>
                </td>
                </tr>
                {% endfor %}
            </table>
</div>

<h4 align="center">Matches</h4><br>
<div class="float-left" style="width: 48%">
                    <table class="table table-striped">
                        <tr>
                            <th>Home Team</th>
                            <th></th>
                            <th>Away Team</th>
                            <th colspan="3">Result</th>
                            <th>Time</th>
                            <th></th>
                        </tr>
                        {% set i = 0 %}
                        {% for match in arrMatch %} 
                        <tr>
                            <td>{{ match.match.homeTeam.name }}</td>
                           <td>-</td>
                           <td>{{ match.match.awayTeam.name }}</td>
                           <td>{{ match.match.score.fullTime.homeTeam }}</td>
                            <td>:</td>
                            <td>{{ match.match.score.fullTime.awayTeam }}</td>
                            <td>{{ match.match.utcDate }} </td>
                            <td><a href="{{ path('delFavMatch',{mid: favMatches[i].id}) }}" class="btn btn-outline-primary btn-sm">Unfollow</a>
                            </td>
                        </tr>
                        {% set i = i + 1 %}
                        {% endfor %} 
                    </table>
        </div>
{% endblock %}

templates/myProfile/user-predict.html.twig
{% extends 'myProfile/user.html.twig' %}

{% block title %}Football results{% endblock %}
{% block body %}
{{ parent() }}
<br>
<form method="POST">
<div class="float-left" style="width: 48%">
        <h4>Upcoming matches within the next 3 days</h4><br>
        <table class="table table-striped">
            <tr>
                <th>HomeTeam</th>
                <th></th>
                <th>AwayTeam</th>
                <th colspan="3">Result</th>
                <th>Time</th>
                <th>Prediction</th>
            </tr>
            {% for match in response.matches %}
            <tr>
                <td>{{ match.homeTeam.name }}</td>
                <td>-</td>
                <td>{{ match.awayTeam.name }}</td>
                <td>{{ match.score.fullTime.homeTeam }}</td>
                <td>:</td>
                <td>{{ match.score.fullTime.awayTeam }}</td>
                <td>{{ match.utcDate }} </td>
                <td><div class="btn-group" role="group" aria-label="Basic example">
                        <a href="{{ path('userPredictSave',{mid: match.id,pred: 'HOME_TEAM'}) }}" class="btn btn-outline-primary btn-sm">1</a>
                        <a href="{{ path('userPredictSave',{mid: match.id,pred: 'DRAW'}) }}" class="btn btn-outline-primary btn-sm">X</a>
                        <a href="{{ path('userPredictSave',{mid: match.id,pred: 'AWAY_TEAM'}) }}" class="btn btn-outline-primary btn-sm">2</a> 
                    </div>
                </td>
            </tr>
             {% endfor %}
        </table>
   </div>
</form>
<h4 align="center">All predictions</h4><br>
<div class="float-right" style="width: 49%">
<table class="table table-striped">
    <tr>
        <th>Home Team</th>
        <th>Away Team</th>
        <th colspan="3">Result</th>
        <th colspan="2">Prediction</th>
    </tr>
    {% set i = 0 %}
    {% for match in arrPred %}
    <tr>
        <td>{{ match.match.homeTeam.name }} - </td>
        <td>{{ match.match.awayTeam.name }}</td>
        <td>{{ match.match.score.fullTime.homeTeam }}</td>
        <td>:</td>
        <td>{{ match.match.score.fullTime.awayTeam }}</td>
        {% if predictions[i].pred == 'HOME_TEAM'  %}
        <td></td>
        <td>1</td>
        {% endif %}
        {% if predictions[i].pred == 'AWAY_TEAM'  %}
        <td></td>
        <td>2</td>
        {% endif %}
        {% if predictions[i].pred == 'DRAW'  %}
        <td></td>
        <td>X</td>
        {% endif %}
    </tr>
    {% set i = i + 1 %}
    {% endfor %}
</table>
</div>
{% endblock %}

templates/myProfile/user-results.html.twig
{% extends 'myProfile/user.html.twig' %}

{% block title %}Football results{% endblock %}
{% block body %}
{{ parent() }}
<br>
<h4 align="center">Results</h4><br>
<div style="width: 40%;margin:0 auto;">
    {% set position = 0 %}
        <div style="height:335px;overflow-y: auto;">
        <table class="table table-striped">
                <tr>
                    <th></th>
                    <th>Username</th>
                    <th>Result</th>
                </tr>
                {% set i = 1 %}
                {% for userRes in usersResults %}
                    {% if userRes == user %}
                    {% set position = i %}
                    {% endif %}
                <tr>
                    <td>{{ i }}.</td>
                    <td>{{ userRes.name }}</td>
                    <td>{{ userRes.result }}</td>
                </tr>
                {% set i = i+1 %}
                {% endfor %}
            </table>
        </div>
    <div style="margin-top: 2%">
        <table class="table table-striped">
            <tr>
                <td>{{ position }}.</td>
                <td>{{ user.name }}</td>
                <td>{{ user.result }}</td>
            </tr>
        </table>
    </div>
        </div>
{% endblock %}

templates/myProfile/user.html.twig
{% extends 'base.html.twig' %}

{% block title %}Football results{% endblock %}
{% block body %}
{{ parent() }}

<ul class="nav nav-tabs" style="background:linear-gradient(to right,#66ccff -3%, #3366cc 100%);margin-top: -0.1%">
    <li class="nav-item">
      <a class="nav-link" href="{{ path('userFavourites')}}" style="color: black">Favourites</a>
    </li>

    <li class="nav-iten">
        <a class="nav-link" href="{{ path('userPredict')}}" style="color: black">Predictions</a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{{ path('userComments')}}" style="color: black">Comments</a>
    </li>

    <li class="nav-item">
        <a class="nav-link" href="{{ path('userQuiz')}}" style="color: black">Quiz</a>
    </li>
</ul>
{% endblock %}